server:
  port: 9000

spring:
  datasource:
    url : jdbc:postgresql://data.leenit.cf:45432/vuespring
    username : kiomnd2
    password : qwer1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create